from metripy.LangAnalyzer.Generic.Metrics.GenericHalSteadAnalyzer import GenericHalSteadAnalyzer


class PythonHalSteadAnalyzer(GenericHalSteadAnalyzer):
    def get_operators(self) -> list[str]:
        return [
            "+",
            "-",
            "*",
            "/",
            "//",
            "%",
            "**",
            "==",
            "!=",
            ">",
            "<",
            ">=",
            "<=",
            "=",
            "+=",
            "-=",
            "*=",
            "/=",
            "%=",
            "//=",
            "**=",
            "and",
            "or",
            "not",
            "&",
            "|",
            "^",
            "~",
            "<<",
            ">>",
            "in",
            "not in",
            "is",
            "is not",
            ":",
            ",",
            ".",
            "(",
            ")",
            "[",
            "]",
            "{",
            "}",
        ]
