from metripy.LangAnalyzer.Generic.Metrics.GenericHalSteadAnalyzer import (
    GenericHalSteadAnalyzer,
)


class TypeScriptHalSteadAnalyzer(GenericHalSteadAnalyzer):
    def get_operators(self) -> list[str]:
        return [
            "+",
            "-",
            "*",
            "/",
            "%",
            "++",
            "--",
            "==",
            "!=",
            "===",
            "!==",
            "<",
            ">",
            "<=",
            ">=",
            "&&",
            "||",
            "!",
            "=",
            "+=",
            "-=",
            "*=",
            "/=",
            "%=",
            "&",
            "|",
            "^",
            "~",
            "<<",
            ">>",
            "?",
            ":",
            ".",
            ",",
            ";",
            "=>",
            "(",
            ")",
            "[",
            "]",
            "{",
            "}",
        ]
